#!/bin/sh

### BEGIN INIT INFO
# Provides:          rtl_sdr
# Required-Start:    $local_fs $network $syslog
# Should-Start:      $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rtl_sdr gps logging
# Description:       rtl_sdr, rtl_mus, rtlrecord.py and gnss-sdr for GPS logging
### END INIT INFO

NAME="rtl_tcp"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/home/sdrgps"
APPBIN1="/usr/local/bin/rtl_tcp"
APPBIN2="/usr/local/share/sdrgps/rtl_mus.py"
APPBIN3="/usr/local/share/sdrgps/rtlrecord.py"
APPBIN4="/usr/local/bin/gnss-sdr"
APPBIN5="/usr/local/share/sdrgps/rotate.py"
APPARGS1=""
APPARGS2=""
APPARGS3=""
APPARGS4="--config_file=/usr/local/share/sdrgps/receiver_complex.conf"
APPARGS5=""
USER="sdrgps"
GROUP="sdrgps"

# Include functions
set -e
. /lib/lsb/init-functions

start() {
  printf "Starting '$NAME'... "
#  start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/rtl_tcp.pid   --chdir "$APPDIR" --exec "$APPBIN1" -- $APPARGS1 || true
#  sleep 1
#  pgrep rtl_tcp && start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/rtl_srv.pid   --chdir "$APPDIR" --exec "$APPBIN2" -- $APPARGS2 || true
#  pgrep rtl_tcp && start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/rtlrecord.pid --chdir "$APPDIR" --exec "$APPBIN3" -- $APPARGS3 || true
#  pgrep rtl_tcp &&
  start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/gnss_sdr.pid  --chdir "$APPDIR" --exec "$APPBIN5" -- $APPARGS5  >> /home/sdrgps/gnss-sdr.log 2>&1 || true
  sleep 1
  start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/gnss_sdr.pid  --chdir "$APPDIR" --exec "$APPBIN4" -- $APPARGS4  >> /home/sdrgps/gnss-sdr.log 2>&1 || true
  printf "done\n"
}

#We need this function to ensure the whole process tree will be killed
killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

stop() {
  printf "Stopping '$NAME'... "
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
  while test -d /proc/$(cat /var/run/$NAME.pid); do
    killtree $(cat /var/run/$NAME.pid) 15
    sleep 0.5
  done 
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
  printf "done\n"
}

status() {
  status_of_proc -p /var/run/$NAME.pid "" $NAME && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
